Repository mattermost-community/mattermost-plugin-todo, pull requests merged in 2020-01, with the labels that each got.

#10 (wip) Go 1.13 and fixing the tests
  Makefile
  build/deploy/main.go
  build/manifest/main.go
  go.mod
  go.sum
  server/bot.go
  server/command.go
  server/main.go
  server/plugin.go
  server/plugin_test.go
  server/store.go
  webapp/.eslintrc.json
  webapp/src/actions.js
  webapp/src/components/modals/full_screen_modal.test.jsx
  webapp/src/components/root/root.jsx
  webapp/src/components/sidebar_right/sidebar_right.jsx
  webapp/src/components/sidebar_right/todo_items.jsx
  webapp/src/index.js
Labels: 2: Dev Review

#16 Bump Mattermost to 5.18
  go.mod
  go.sum
Labels: 2: Dev Review

#18 Fix empty task
  server/command.go
Labels: 3: Reviews Complete

#20 [GH-19] Add markdown support to Todos
  webapp/src/components/sidebar_right/todo_items.jsx
Labels: 3: Reviews Complete

#26 command - /todo returns the list of todos
  server/command.go
Labels: 2: Dev Review, QA Review Done
