Repository mattermost-community/mattermost-plugin-todo, pull requests merged in 2020-03, with the labels that each got.

#27 [GH-12] Request a task from another user
  README.md
  plugin.json
  server/bot.go
  server/command.go
  server/issue.go
  server/item.go
  server/list.go
  server/plugin.go
  server/store.go
  webapp/src/action_types.js
  webapp/src/actions.js
  webapp/src/components/buttons/accept.jsx
  webapp/src/components/buttons/bump.jsx
  webapp/src/components/buttons/complete.jsx
  webapp/src/components/buttons/remove.jsx
  webapp/src/components/post_type_todo/index.js
  webapp/src/components/post_type_todo/post_type_todo.jsx
  webapp/src/components/root/index.js
  webapp/src/components/root/root.jsx
  webapp/src/components/root/root.scss
  webapp/src/components/sidebar_right/index.js
  webapp/src/components/sidebar_right/sidebar_right.jsx
  webapp/src/components/sidebar_right/sidebar_right.scss
  webapp/src/components/sidebar_right/todo_issues.jsx
  webapp/src/components/sidebar_right/todo_items.jsx
  webapp/src/components/user_selector/autocomplete_selector.jsx
  webapp/src/components/user_selector/generic_user_provider.jsx
  webapp/src/components/user_selector/provider.jsx
  webapp/src/components/user_selector/quick_input.jsx
  webapp/src/components/user_selector/suggestion.jsx
  webapp/src/components/user_selector/suggestion_box.jsx
  webapp/src/components/user_selector/suggestion_list.jsx
  webapp/src/constants.jsx
  webapp/src/index.js
  webapp/src/reducer.js
  webapp/src/selectors.js
  webapp/src/utils.js
Labels: 2: Dev Review, QA Review Done

#37 Follow up
  server/manifest.go
  webapp/.gitignore
  webapp/junit.xml
  webapp/package.json
  webapp/src/manifest.js
Labels: 3: Reviews Complete

#39 Update npm dependencies
  webapp/package-lock.json
  webapp/package.json
Labels: 3: Reviews Complete, QA Review Done

#44 [GH43] Fix 'When no SiteURL is set in config, the basePath is not properly set'
  webapp/src/actions.js
Labels: 3: Reviews Complete, QA Review Done
