Repository mattermost-community/mattermost-plugin-todo, pull requests merged in 2022-09, with the labels that each got.

#180 GH-177 - Minor UI tweaks and regression fix
  webapp/src/components/add_issue/add_issue.jsx
  webapp/src/components/add_issue/index.js
  webapp/src/components/sidebar_right/sidebar_right.jsx
  webapp/src/components/sidebar_right/sidebar_right.scss
  webapp/src/components/todo_item/todo_item.jsx
  webapp/src/widget/menu.scss
Labels: 4: Reviews Complete

#182 Minor UI Fixes for todo items
  webapp/src/components/buttons/accept.jsx
  webapp/src/components/sidebar_right/_todo-item.scss
  webapp/src/components/sidebar_right/sidebar_right.jsx
  webapp/src/components/sidebar_right/sidebar_right.scss
  webapp/src/components/todo_item/todo_item.jsx
  webapp/src/widget/todo_toast/todo_toast.scss
Labels: 2: Dev Review, 3: QA Review

#189 Updating todo UI fixes
  webapp/src/components/buttons/remove.jsx
  webapp/src/components/post_type_todo/post_type_todo.jsx
  webapp/src/components/sidebar_right/sidebar_right.scss
Labels: 2: Dev Review, QA Review Done

#190 MM-47046/MM-47052 Use version of React DOM provided by web app
  webapp/webpack.config.js
Labels: 4: Reviews Complete
